repos:
  - repo: https://github.com/CadWalaDers/dk-ui
    rev: v3.2.0
    hooks:
      - id: prettier
        name: Prettier
        entry: node_modules/.bin/prettier
        types: [javascript, jsx, vue, json, md, yml, yaml, css, scss, less]
