name: DK plus Ui Github Actions

# 当 master 分支 push 代码的时候触发 workflow
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 下载仓库代码 / 校验
      - name: Checkout
        # actions/checkout@v3 是 github 官方的一个action，用于 clone 该仓库的源码到工作流中
        uses: actions/checkout@v3

      # 安装 pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.18.2

      # 安装 node
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'pnpm'

      # 安装依赖项
      - name: pnpm Install
        run: pnpm install

      - name: npm Build:docs
        run: npm run build:docs

      - name: Deploy to Web Server
        uses: easingthemes/ssh-deploy@v2
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          SOURCE: /docs/.vitepress/dist
          TARGET: ${{ secrets.TARGET }}

      - name: Copy files to target directory
        run: |
          ssh -i "$SSH_PRIVATE_KEY" -p ${{ secrets.REMOTE_PORT }} ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "
            # 获取当前时间
              current_time=\$(date +'%Y%m%d%H%M%S')
            # 文件目录
              rootPath=\${{ secrets.TARGET }}
              path=\${{ secrets.path }}
              rootFolder='BackupCopy'
              cd \${rootPath}
              mkdir -p _backUp/\${rootFolder}_\${current_time}
              cp -r \${path} _backUp/\${rootFolder}_\${current_time}/
              rm -rf \${path}
          "
