name: DK plus Ui Github Actions

# 当 master 分支 push 代码的时候触发 workflow
on:
  push:
    branches:
      - master
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 下载仓库代码 / 校验
      - name: Checkout
        # actions/checkout@v3 是 github 官方的一个action，用于 clone 该仓库的源码到工作流中
        uses: actions/checkout@v3

      # 安装 pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.18.2

      # 安装 node
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'pnpm'

      # 安装依赖项
      - name: Install
        run: pnpm install

      - name: Build(docs)
        run: npm run build:docs

      - name: Build(play)
        run: npm run build:play

      - name: Create SSH directory
        run: mkdir -p $HOME/.ssh

      - name: Create known_hosts file
        run: touch $HOME/.ssh/known_hosts

      - name: Clear dk-plus.com directory
        if: github.ref == 'refs/heads/dev'
        run: |
          ssh-keyscan -t rsa ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} -p ${{ secrets.REMOTE_PORT }} "rm -rf /www/wwwWeb/test.cadwaladerss.com*"

      - name: Deploy to Web Server (dev)
        if: github.ref == 'refs/heads/dev'
        uses: easingthemes/ssh-deploy@v2
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          SOURCE: /play/dist/*
          TARGET: /www/wwwWeb/test.cadwaladerss.com

      - name: Clear dk-plus.com directory
        if: github.ref == 'refs/heads/master'
        run: |
          ssh-keyscan -t rsa ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} -p ${{ secrets.REMOTE_PORT }} "rm -rf /www/wwwWeb/dk-plus.com/*"

      - name: Deploy to Web Server (master)
        if: github.ref == 'refs/heads/master'
        uses: easingthemes/ssh-deploy@v2
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          SOURCE: /docs/.vitepress/dist/*
          TARGET: /www/wwwWeb/dk-plus.com
