name: DK plus Ui Github Actions

# 当 master 分支 push 代码的时候触发 workflow
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 下载仓库代码 / 校验
      - name: Checkout
        # actions/checkout@v3 是 github 官方的一个action，用于 clone 该仓库的源码到工作流中
        uses: actions/checkout@v3

      # 安装 pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.18.2

      # 安装 node
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'pnpm'

      # 安装依赖项
      - name: Install
        run: pnpm install

      - name: Build
        run: npm run build:docs

      - name: Deploy to Web Server
        uses: easingthemes/ssh-deploy@v2
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: 6098
          SOURCE: /docs/.vitepress/dist
          TARGET: /www/wwwroot/dk-plus.com

      - name: Copy files to target directory
        run: |
          ssh -p 6098 ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "cp -R /www/wwwroot/dk-plus.com/dist. /www/wwwroot/dk-plus.com"
