name: DK plus Ui Github Actions

# 当 master 分支 push 代码的时候触发 workflow
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 下载仓库代码 / 校验
      - name: Checkout
        # actions/checkout@v3 是 github 官方的一个action，用于 clone 该仓库的源码到工作流中
        uses: actions/checkout@v3

      # 安装 pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.18.2

      # 安装 node
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'pnpm'

      # 安装依赖项
      - name: Install
        run: pnpm install

      - name: Build
        run: npm run build:docs

      - name: Deploy to Web Server
        uses: easingthemes/ssh-deploy@v2
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
<<<<<<< HEAD
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          SOURCE: /docs/.vitepress/dist/*
          TARGET: /www/wwwWeb/dk-plus.com
=======
          REMOTE_PORT: 6098
          SOURCE: /docs/.vitepress/dist
          TARGET: /www/wwwroot/dk-plus.com

      - name: Copy files to target directory
        run: |
          ssh -i "$SSH_PRIVATE_KEY" -p "$REMOTE_PORT" "$REMOTE_USER"@"$REMOTE_HOST" "
            # 移动目录或文件到目标位置
            mv \$SOURCE \$TARGET

            # 获取当前时间并重命名目标位置的目录或文件为当前时间加 _docs_dist_git
            current_time=\$(date +'%Y%m%d%H%M%S')
            mv \$TARGET \$TARGET/\$current_time\_docs_dist_git
          "
>>>>>>> b348bd2 (perf: 1.设置自动部署)
